### PR TITLE
Closing RPE app in Windows leaves the backend server running in some instances causing clashes on new rpe instance

### PR DESCRIPTION
**Pull request by shivaahir158**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [x] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details - 

1. Added signal handlers in restapi_server.py to handle SIGINT and SIGTERM shutdowns for the Flask server.
2. Implemented a server_shutdown function to log and execute the backend shutdown process cleanly upon receiving a shutdown signal.
3. Created a Playwright test to launch and close the Electron app 10 times (can do 100 times as well, but job run would be time consuming on CI, while testing I do an iteration of 100), checks that no lingering processes remain.
4. Commented out dsp.test.js and clocking.test.js for now, I will uncomment them again when we shall have proper testing suites, for now doing e2e for app launch, restart, and checking if the app process is killed.
5. Backend PR #263

> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Frontend: <Specify frontend components>
> - [x] Backend: <Specify backend components>restapi_server.py
> - [ ] Library: <Specify the library name, e.g. npm packages>
> - [ ] Plug-in: <Specify the plugin name, e.g. Webpack, jtest>
> - [ ] Documentation
> - [x] Playwright tests restart.test.js,  dsp.test.js, clocking.test.js
> - [ ] Continuous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break backward-compatibility. If so, please list who may be influenced.

User can verify if the process has shut down, in the log file, fyi @NadeemYaseen  : 

image

### CODE REVIEW

**Review by ravikiranchollangi — CHANGES_REQUESTED** [review]
Let's not comment out the e2e tests. You can re-factor later. 
How long does the 10times re-launch test case take?

**Comment by shivaahir158** [comment]
> Let's not comment out the e2e tests. You can re-factor later. How long does the 10times re-launch test case take?

@ravikiranchollangi , 10 iterations takes around 45s, also, I will push all the e2e test cases in the next PR, it needed some fixes which is been done, requesting to fix this PR so we have a solution for Shutdown issue, and I shall raise one more PR for the e2e test cases.

**Comment by shivaahir158** [comment]
> > Let's not comment out the e2e tests. You can re-factor later. How long does the 10times re-launch test case take?
> 
> @ravikiranchollangi , 10 iterations takes around 45s, also, I will push all the e2e test cases in the next PR, it needed some fixes which is been done, requesting to for your approval to this PR so we have a solution for Shutdown issue, and I shall raise one more PR for the e2e test cases.

@ravikiranchollangi SIGTERM is not a forced shutdown, to my knowledge, it’s a polite request for the process to terminate. When a process receives SIGTERM, it has the opportunity to perform any cleanup tasks before it exits, such as closing files, saving state, or logging. This makes SIGTERM a preferred way to smoothly (not forcibly) stop a process. SIGKILL is a forced shutdown.

I believe SIGTERM is not essential if SIGINT is the only signal sent by the frontend, but keeping both signals allows our backend to smoothly handle termination requests.

**Comment by NadeemYaseen** [comment]
Adding a screenshot confirms that the backend honors the kill signal sent by the front end.

**Comment by shivaahir158** [comment]
@NadeemYaseen , check the lastest changes, as discussed, I have created shutdown.py API, called the same api in restapi_server.py, and in cleanup.js, I have called the shutdown api, please check the changes once, so we can discuss further.

**Comment by shivaahir158** [comment]
@NadeemYaseen , fetch the latest changes, just removed the need to have axios and called the shutdown function in serverapi.js, and after that called n cleanup.js.

**Comment by shivaahir158** [comment]
@NadeemYaseen , fixed. check now.

**Pull request closed without merging**
