### PR TITLE
Setting up e2e under test GitHub ci setup

### PR DESCRIPTION
**Pull request by NadeemYaseen**
> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ x] Breaking new feature. If so, please describe details in the description part.

Setting up E2E test in GH CI.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Frontend: <Specify frontend components>
> - [ ] Backend: <Specify backend components>
> - [ ] Library: <Specify the library name, e.g. npm packages>
> - [ ] Plug-in: <Specify the plugin name, e.g. Webpack, jtest>
> - [ ] Documentation
> - [ ] Regression tests
> - [x ] Continuous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break backward-compatibility. If so, please list who may be influenced.

### CODE REVIEW

**Comment by NadeemYaseen** [comment]
@shivaahir158 The CI was passed on Friday, see [here](https://github.com/os-fpga/rapid_power_estimator/actions/runs/11519607987) but now it is failing with the error below like [this](https://github.com/os-fpga/rapid_power_estimator/actions/runs/11576642745/job/32226111548#step:13:139)
Can you look into this by cloning my branch and running a test locally to confirm this is purely a CI error? 
By the way, 2 tests are passing in CI.

**Comment by shivaahir158** [comment]
@NadeemYaseen check now

**Comment by ravikiranchollangi** [comment]
> 
> 
> @NadeemYaseen check now
> 
> 

Thanks @shivaahir158, could you please explain the fix to selectors ? Why we didn't catch it in previous commits or locally ?

**Comment by ravikiranchollangi** [comment]
> 
> 
> @NadeemYaseen check now
> 
> 

Thanks @shivaahir158, could you please explain the fix to selectors ? Why we didn't catch it in previous commits or locally ?

**Comment by shivaahir158** [comment]
> > @NadeemYaseen check now
> 
> Thanks @shivaahir158, could you please explain the fix to selectors ? Why we didn't catch it in previous commits or locally ?

@ravikiranchollangi , I have fixed the selector for clicking on 'ok' button after giving inputs to clocking, it was not clicking on it, but I fixed the selector for it, and the jobs are ok. The selector for the OK button in the test was updated because the class name changed in the UI from niikz0 to apm68, causing the test to fail.

**Review by shivaahir158 — APPROVED** [review]

**Pull request merged**
