### PR TITLE
Add pytest into github action and added initial unit tests code

### PR DESCRIPTION
**Pull request by GuanYung**
Added initial backend module unit tests to cover the clock and utilities module.
Added github action to enable the tests during CI build.

pytest local run 
image

### CODE REVIEW

**Review by volodymyrkochyn — APPROVED** [review]

**Review by chernyee — APPROVED** [review]

**Comment by ravikiranchollangi** [comment]
@NadeemYaseen can we enable these for CI when this is merged ?

**Comment by NadeemYaseen** [comment]
> @NadeemYaseen can we enable these for CI when this is merged ?

@GuanYung already has fixed issues related to CI and they are running. So I believe they are already enabled. Is there anything else left?

**Review by NadeemYaseen — APPROVED** [review]

**Comment by ravikiranchollangi** [comment]
> > @NadeemYaseen can we enable these for CI when this is merged ?
> 
> 
> 
> @GuanYung already has fixed issues related to CI and they are running. So I believe they are already enabled. Is there anything else left?

Yes, why don't we have Windows in CI?

**Comment by NadeemYaseen** [comment]
> > > @NadeemYaseen can we enable these for CI when this is merged ?
> > 
> > 
> > @GuanYung already has fixed issues related to CI and they are running. So I believe they are already enabled. Is there anything else left?
> 
> Yes, why don't we have Windows in CI?

This is windows
https://github.com/os-fpga/rapid_power_estimator/actions/runs/7982238691/job/21795413119?pr=13

**Comment by GuanYung** [comment]
I will need to update the code again as it is taking too long to merge in.. There were some refactoring happen in the other PR that causing the test to fail.

**Pull request merged**
