### PR TITLE
 Add Unit Tests for RsMessage and BRAM Modules - task/RPE-52/Unit-tests-PyTest-for-RPE

### PR DESCRIPTION
**Pull request by shivaahir158**
### Motivate of the pull request
 - [x] To address an existing issue. If so, please provide a link to the issue: 
 - [ ] Breaking new feature. If so, please describe details in the description part.

### Describe the technical details
Adding PyTests to the existing submodules which is crucial to find the results confirming that the modules behave as intended. The tests will be part of the standard testing suite and should be run regularly to ensure reliability and quality of the code.

 ### Which part of the code base require a change
 
 - [ ] Frontend: Project file
 - [x] Backend: PyTests for all submodules
 - [ ] Library: <Specify the library name, e.g. npm packages>
 - [ ] Plug-in: <Specify the plugin name, e.g. Webpack, jtest>
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continuous Integration (CI) scripts

### CODE REVIEW

**Comment by chernyee** [comment]
Please use the predefined PR template.

**Comment by chernyee** [comment]
I saw there is a lot of error in the test cases. Please fix them and run the test case locally to verify no error before push the changes.

**Comment by ravikiranchollangi** [comment]
@shivaahir158 please fix the CI

**Comment by shivaahir158** [comment]
> @shivaahir158 please fix the CI

Hi @ravikiranchollangi , yes, I am 24 tests are passing and 10 are failing, I am working on that.

**Comment by ravikiranchollangi** [comment]
> > @shivaahir158 please fix the CI
> 
> 
> 
> Hi @ravikiranchollangi , yes, I am 24 tests are passing and 10 are failing, I am working on that.
> 
> 

Please re-open when it's ready.

**Pull request closed without merging**
